/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gitTestProject;

public class Library {
	public static void main(String[] args) {
		System.out.println("____________________________");
		System.out.println("############################");
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
	}
    public boolean someLibraryMethod() {
        return true;
    }
}
